In [8]:
import numpy as np
from scipy.signal import convolve2d

image = np.array([[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                  [0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0],
                  [0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0],
                  [0,0,1,1,1,1,1,0,0,0,0,1,1,1,0,0],
                  [0,0,1,1,1,1,0,0,0,0,1,1,1,1,0,0],
                  [0,0,0,1,1,0,0,0,0,1,1,1,1,1,0,0],
                  [0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0],
                  [0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0],
                  [0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0],
                  [0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0],
                  [0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0],
                  [0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0],
                  [0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]], dtype = float)

kernels = np.array([[1,1,1],
                    [1,1,1],
                    [1,1,1]], dtype = float)

# x = np.copy(image)
# output = np.zeros(x.shape)

# tes1 = np.matrix(x)
# tes2 = np.matrix(kernels)

# kernel_height, kernel_width = kernels.shape

# for i in range(image.shape[0] - kernels.shape[0] + 1):
#     for j in range(image.shape[1] - kernels.shape[1] + 1):
#         region = image[i:i + kernels.shape[0], j:j + kernels.shape[1]]
#         convolution_result = np.sum(region * kernels)
#         output[i, j] = 1 if convolution_result > 0 else 0


# print(output)

# np.matmul(tes1, tes2)

# Perform 2D convolution
result = convolve2d(image, kernels, mode='valid')

# Apply thresholding
thresholded_result = np.where(result > 0, 1, 0)

# The 'thresholded_result' variable now contains the thresholded result
print(thresholded_result)

# The 'result' variable now contains the result of the convolution
# print(result)

[[0 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 0 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 0 0]]


In [ ]:
dilated = np.array([[0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],
                    [1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0.],
                    [1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0.],
                    [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.],
                    [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.],
                    [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.],
                    [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.],
                    [0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.],
                    [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.],
                    [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.],
                    [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.],
                    [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.],
                    [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.],
                    [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
                    [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]])

In [9]:
import numpy as np

def convolution_2d(image, kernel):
    image_height, image_width = image.shape
    kernel_height, kernel_width = kernel.shape
    result_height = image_height - kernel_height + 1
    result_width = image_width - kernel_width + 1
    result = np.zeros((result_height, result_width))

    for i in range(result_height):
        for j in range(result_width):
            result[i, j] = np.sum(image[i:i+kernel_height, j:j+kernel_width] * kernel)

    return result

image = np.array([[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                  [0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0],
                  [0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0],
                  [0,0,1,1,1,1,1,0,0,0,0,1,1,1,0,0],
                  [0,0,1,1,1,1,0,0,0,0,1,1,1,1,0,0],
                  [0,0,0,1,1,0,0,0,0,1,1,1,1,1,0,0],
                  [0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0],
                  [0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0],
                  [0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0],
                  [0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0],
                  [0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0],
                  [0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0],
                  [0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]], dtype=float)

kernel = np.array([[1,1,1],
                  [1,1,1],
                  [1,1,1]], dtype=float)

result = convolution_2d(image, kernel)

# Apply thresholding
thresholded_result = np.where(result > 0, 1, 0)

# The 'thresholded_result' variable now contains the thresholded result
print(thresholded_result)


[[0 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 0 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 0 0]]


In [10]:
def convolution(image, kernel, kernelSize):
  img = np.copy(image)
  output = np.zeros(img.shape)

  padding = np.pad(img, pad_width = kernelSize//2, mode = 'constant')
  for i in range(img.shape[0]):
    for j in range(img.shape[1]):
      for k in range(kernel.shape[0]):
        for l in range(kernel.shape[1]):
          output[i][j] = output[i][j] + kernel[k][l] * padding[i+k][j+l]
  
  output = np.where(output > 1, 1, 0)

  return output


image = np.array([[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                  [0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0],
                  [0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0],
                  [0,0,1,1,1,1,1,0,0,0,0,1,1,1,0,0],
                  [0,0,1,1,1,1,0,0,0,0,1,1,1,1,0,0],
                  [0,0,0,1,1,0,0,0,0,1,1,1,1,1,0,0],
                  [0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0],
                  [0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0],
                  [0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0],
                  [0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0],
                  [0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0],
                  [0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0],
                  [0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]], dtype = float)

kernels = np.array([[1,1,1],
                    [1,1,1],
                    [1,1,1]], dtype = float)


Ix = convolution(image, kernels, 3)
Ix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])